version: '3'
services: 
    react-app:
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports: 
            - "4000:3000"
        volumes: 
            - /app/node_modules
            - .:/app
        environment: 
            - CHOKIDAR_USEPOLLING=true